# Generated by Django 3.0.7 on 2020-06-09 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwaards_app', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='content',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rate',
            name='usability',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
